### ISSUE TITLE
Add correct error codes for when things go wrong for the tcp provider

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom-for-firefox#8]
The current interface doesn't surface any errors. We should do something like we do in the chrome tcp-sockets provider; and we should make an interface that subsumes both sets of errors with some consistent error-codes that are added as part of the tcp-sockets interface (and do the same for udp-sockets). The freedom issue is here: https://github.com/freedomjs/freedom/issues/69

**Comment by soycode** [comment]
This was partially addressed with: https://github.com/freedomjs/freedom-for-firefox/pull/56

Since the tests themselves are still being fixed though (https://github.com/freedomjs/freedom-for-firefox/issues/50) there may be some outstanding issues. Also, the above change just corrected the errors being reported to be consistent with the Chrome provider/freedom interface - it didn't provide a comprehensive mapping of errors as in the Chrome provider. I'd say making such a map should still be a goal.

**Comment by soycode** [comment]
The tests are fixed and I believe this issue is addressed, at least to the point of parity with the existing API.
